www1/comments/urls.py
from django.urls import path
from . import views
from . import forms

app_name = "comments"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/update/", views.UpdateView.as_view(), name="edit"),
]

www1/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

www1/www1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("comments/", include("comments.urls")),
    path("admin/", admin.site.urls),
]

www1/comments/models.py
from django.db import models

class Comment(models.Model):
    text = models.CharField(max_length=500)
    author = models.CharField(max_length=100)
    creation_date = models.DateField(default=None)
    published_from = models.DateField(default=None)

www1/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

www1/comments/forms.py
from django import forms
from .models import Comment
from django.utils import timezone


class CreateForm(forms.Form):
    text = forms.CharField(max_length=500, label="Comment text")
    author = forms.CharField(max_length=100, label="Author")
    published_from = forms.DateField()
        
    def create_comment(self):
        data = self.cleaned_data
        Comment(text = data["text"], author = data["author"], 
                creation_date = timezone.now(), published_from = data["published_from"]).save()

www1/comments/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from .models import Comment
from django.db.models import F
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .forms import CreateForm

class IndexView(generic.ListView):
    template_name = "comments/index.html"
    context_object_name = "comment_list"

    def get_queryset(self):
        return Comment.objects.all()


class CreateView(generic.FormView):
    template_name = "comments/create.html"
    form_class = CreateForm
    success_url = "/comments"
    
    def form_valid(self, form) -> HttpResponse:
        form.create_comment()
        return super().form_valid(form)
    
    
class DetailView(generic.DetailView):
    model = Comment
    template_name = "comments/detail.html"
    def get_queryset(self):
        return Comment.objects.filter(published_from__lte=timezone.now())
    

class UpdateView(generic.UpdateView):
    model = Comment
    fields = ["text", "published_from"]
    success_url = "/comments"
    template_name = "comments/update.html"

www1/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from .models import Question, Choice
from django.db.models import F
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

www1/comments/templates/comments/create.html
<form action="/comments/create/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

www1/comments/templates/comments/detail.html
<h2>Author: {{  comment.author }}</h2>
<p>{{  comment.text  }}</p>
<p>Created on {{  comment.creation_date  }}</p>
<p>Published from {{  comment.published_from  }}</p>
<a href = "/comments/{{  comment.pk  }}/update">Edit</a>

www1/comments/templates/comments/index.html
{% load static %}
<a href="/comments/create">Add Comment</a>
{% if comment_list %}
    <ul>
    {% for comment in comment_list %}
        <li><a href="/comments/{{ comment.id }}/">{{ comment.text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No comments are available.</p>
{% endif %}

www1/comments/templates/comments/update.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

www1/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

www1/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

www1/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

www1/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<div id="site-name"><a href="{% url 'admin:index' %}">
  {% block branding %}
  <div id="site-name"><a href="{% url 'admin:index' %}">Polls Administration</a></div>
  {% if user.is_anonymous %}
    {% include "admin/color_theme_toggle.html" %}
  {% endif %}
  {% endblock %}
</a></div>
{% if user.is_anonymous %}
  {% include "admin/color_theme_toggle.html" %}
{% endif %}
{% endblock %}

{% block nav-global %}{% endblock %}